namespace AFFHA.Domain
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    /// <summary>
    /// BaseEntity class for all Entities.
    /// </summary>
    public class BaseEntity
    {
        /// <summary>
        /// An unique identifier generated by the database.
        /// </summary>
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
    }
}